name: Build WAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B clean package -Pprod

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: aet-api-war
          path: target/*.war
